In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [56]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [57]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [58]:
## Define the vocabulary size
voc_size=10000

In [59]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [60]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[4154, 6084, 7015, 5339],
 [4154, 6084, 7015, 9020],
 [4154, 9281, 7015, 4588],
 [1816, 5219, 3336, 6454, 3234],
 [1816, 5219, 3336, 6454, 2319],
 [4293, 4154, 2785, 7015, 267],
 [5936, 8452, 6653, 6454]]

In [61]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
# sent_length=8 # deprecated
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4154 6084 7015 5339]
 [   0    0    0    0 4154 6084 7015 9020]
 [   0    0    0    0 4154 9281 7015 4588]
 [   0    0    0 1816 5219 3336 6454 3234]
 [   0    0    0 1816 5219 3336 6454 2319]
 [   0    0    0 4293 4154 2785 7015  267]
 [   0    0    0    0 5936 8452 6653 6454]]


In [65]:
## feature representation
dim=10

In [71]:
model=Sequential()
model.add(Embedding(voc_size,dim)) # input_length=sent_length (deprecated)
model.compile('adam','mse')

In [72]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [73]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[[-0.0254512 ,  0.00258302, -0.00795947, -0.02966337,
          0.02352592, -0.03877814, -0.04386593, -0.04524684,
         -0.00778113, -0.03742666],
        [-0.0254512 ,  0.00258302, -0.00795947, -0.02966337,
          0.02352592, -0.03877814, -0.04386593, -0.04524684,
         -0.00778113, -0.03742666],
        [-0.0254512 ,  0.00258302, -0.00795947, -0.02966337,
          0.02352592, -0.03877814, -0.04386593, -0.04524684,
         -0.00778113, -0.03742666],
        [-0.0254512 ,  0.00258302, -0.00795947, -0.02966337,
          0.02352592, -0.03877814, -0.04386593, -0.04524684,
         -0.00778113, -0.03742666],
        [-0.01213012, -0.0147946 ,  0.0393875 , -0.01207265,
          0.04120183, -0.01754596,  0.04045257,  0.04385798,
         -0.03761018, -0.00973892],
        [-0.00226239, -0.00821222, -0.04904526,  0.04673189,
         -0.01383074,  0.0408912 , -0.0148536 , -0.02140206,
         -0.01395608, -0.02074045],
        [ 0.0085991 ,  0.00370488,  0.04080797,  0.0

In [48]:
embedded_docs[0]

array([   0,    0,    0,    0, 4154, 6084, 7015, 5339], dtype=int32)